# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectposition',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projectpositionapplication',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectpositionapplication',
            name='position',
        ),
        migrations.RemoveField(
            model_name='projectpositionapplication',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectPosition',
        ),
        migrations.DeleteModel(
            name='ProjectPositionApplication',
        ),
    ]
