# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170609_1039'),
        ('project', '0002_auto_20170612_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPositionSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='projectposition',
            name='timeline',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectposition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectpositionapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPosition', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='projectpositionapplication',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('S', 'Selected'), ('R', 'Rejected')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='projectpositionskill',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPosition', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='projectpositionskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Skill', verbose_name='Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpositionskill',
            unique_together=set([('position', 'skill')]),
        ),
    ]
