# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170615_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposition',
            name='timeline',
            field=models.CharField(default='', max_length=32),
        ),
    ]
